version: '3.5'
services:
  BAP_pymc3:
    container_name: BAP_pymc3
    build: .
    image: bap_pymc3:latest
#    runtime: nvidia
#    environment:
#      - NVIDIA_VISIBLE_DEVICES=all
#      - ./web.env
#    command: nvidia-smi
    tty: true
    command: /bin/bash
    volumes:
      - .:/src
#    env_file:
#      - ./web.env
    ports:
      - "8001:8001"

  BAP_pymc3jax:
    container_name: BAP_pymc3jax
    build:
      context: .
      dockerfile: pymc3jax.Dockerfile
    image: bap_pymc3jax:latest
    #    runtime: nvidia
    #    environment:
    #      - NVIDIA_VISIBLE_DEVICES=all
    #      - ./web.env
    #    command: nvidia-smi
    tty: true
    command: /bin/bash
    volumes:
      - .:/src
    #    env_file:
    #      - ./web.env
    ports:
      - "8002:8002"

  BAP_gpu:
    container_name: BAP_gpu
    build:
      context: .
      dockerfile: gpu.Dockerfile
    image: bap_gpu:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    tty: true
    ipc: 'host'
    stdin_open: true
    command: /bin/bash
    volumes:
      - .:/src
    #    env_file:
    #      - ./web.env
    ports:
      - "8003:8003"